### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by RYANZYC** [ethz-asl/pcl_catkin#17]
Hello maintainer!
I want to use your  yumi- stacking version metapackage in 16.04 kinetic.But I could not catkin_make successful.Here are my related package and error.What version of ROS do you use?
![2019-03-30 16-13-54屏幕截图](https://user-images.githubusercontent.com/34129622/55273507-738ce200-5307-11e9-9a1b-d3fc2b63d2d7.png)
![2019-03-30 16-14-38屏幕截图](https://user-images.githubusercontent.com/34129622/55273510-7982c300-5307-11e9-843e-e23753a05857.png)
![2019-03-30 16-15-11屏幕截图](https://user-images.githubusercontent.com/34129622/55273511-7d164a00-5307-11e9-9c35-029a9e9bbc19.png)

Looking forward to your reply,thanks!

**Comment by margaritaG** [comment]
@RYANZYC looks like a PCL related error: https://github.com/PointCloudLibrary/pcl/issues/2899

We have just now updated this repository to fetch the latest release of PCL (1.10.1). You could try to pull our latest changes and try building again, maybe those issues were resolved in the last release. 
If all fails, I would ask reopen the issue I linked you directly in the PCL repository.

**Comment by GEC-xjtu** [comment]
I successfully installed `tensorflow` and `tensorflow_ros_cpp`, but when I run `catkin build segmapper`, an error occurred during the compilation of` pcl_catkin`

```
Errors     << pcl_catkin:make /home/iairloc/Catkin/LOL/logs/pcl_catkin/build.make.005.log                                                                                                                  
//usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5: undefined reference to QWindowSystemInterface::registerTouchDevice(QTouchDevice*)
//usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5: undefined reference to QQuickFlickable::contentItem()
collect2: error: ld returned 1 exit status
make[5]: *** [bin/pcl_openni_grabber_example] Error 1
make[4]: *** [io/tools/CMakeFiles/pcl_openni_grabber_example.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
```

I guess my system has some problems, but I don’t know how to solve it. Could you help me solve it?
